FROM python:3.9

RUN pip install pipenv

WORKDIR /app
COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pipenv install --system --deploy

COPY ["predict.py", "model.bin", "./"]

EXPOSE 5002

ENTRYPOINT [ "gunicorn","--bind","localhost:8888","predict:app"]
